name: Check HTTP Logs

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository code
        uses: actions/checkout@v6

      - name: Check for errors
        run: |
          echo "Checking HTTP Status Codes..."
          ruby << "RUBY"
          errors = []
          File.foreach("access.log") do |line|
            status = line.split[8].to_i
            if status < 200 || status > 299
              errors << line
            end
          end
          if errors.any? 
            puts "Errors found:"
            puts errors
            exit 1
          else
            puts "All responses successful"
          end
          RUBY





